"""Prototype in-memory data store used by API views.

In production, replace this with Django models + database queries.
"""

PATIENTS = [
    {
        "id": "PT-001",
        "firstName": "Jane",
        "lastName": "Doe",
        "dateOfBirth": "1985-03-15",
        "gender": "Female",
        "bloodType": "O+",
        "nfcId": "MED-2847-NFC",
        "status": "active",
        "room": "ICU-204",
        "admissionDate": "2026-02-10",
        "allergies": ["Penicillin", "Sulfa Drugs"],
        "primaryDiagnosis": "Acute Myocardial Infarction",
        "insuranceProvider": "BlueCross BlueShield",
        "insuranceId": "BCB-449281",
        "emergencyContact": {
            "name": "John Doe",
            "relationship": "Spouse",
            "phone": "(555) 123-4567",
        },
        "medications": [
            {"name": "Aspirin", "dosage": "81mg", "frequency": "Daily"},
            {"name": "Metoprolol", "dosage": "50mg", "frequency": "Twice daily"},
            {"name": "Atorvastatin", "dosage": "40mg", "frequency": "Nightly"},
        ],
        "vitalSigns": {
            "heartRate": 78,
            "bloodPressure": "128/82",
            "temperature": 98.6,
            "oxygenSaturation": 97,
        },
        "medicalHistory": [
            "Hypertension (diagnosed 2018)",
            "Type 2 Diabetes (diagnosed 2020)",
            "Appendectomy (2005)",
        ],
        "notes": [
            "Patient stable post-procedure. Continue monitoring.",
            "Scheduled for cardiac rehabilitation assessment.",
        ],
    },
    {
        "id": "PT-002",
        "firstName": "Marcus",
        "lastName": "Rivera",
        "dateOfBirth": "1972-07-22",
        "gender": "Male",
        "bloodType": "A-",
        "nfcId": "MED-3912-NFC",
        "status": "critical",
        "room": "ICU-102",
        "admissionDate": "2026-02-18",
        "allergies": ["Latex", "Iodine"],
        "primaryDiagnosis": "Severe Pneumonia",
        "insuranceProvider": "Aetna",
        "insuranceId": "AET-882104",
        "emergencyContact": {
            "name": "Sofia Rivera",
            "relationship": "Wife",
            "phone": "(555) 987-6543",
        },
        "medications": [
            {"name": "Levofloxacin", "dosage": "750mg", "frequency": "Daily IV"},
            {"name": "Albuterol", "dosage": "2.5mg", "frequency": "Every 4 hours"},
            {"name": "Prednisone", "dosage": "40mg", "frequency": "Daily"},
        ],
        "vitalSigns": {
            "heartRate": 102,
            "bloodPressure": "145/92",
            "temperature": 101.2,
            "oxygenSaturation": 91,
        },
        "medicalHistory": [
            "COPD (diagnosed 2015)",
            "Former smoker (quit 2016)",
            "Hip replacement (2019)",
        ],
        "notes": [
            "Oxygen therapy initiated. Monitoring closely.",
            "Awaiting CT scan results.",
        ],
    },
    {
        "id": "PT-003",
        "firstName": "Emily",
        "lastName": "Chen",
        "dateOfBirth": "1998-11-03",
        "gender": "Female",
        "bloodType": "B+",
        "nfcId": "MED-1204-NFC",
        "status": "active",
        "room": "3B-412",
        "admissionDate": "2026-02-15",
        "allergies": [],
        "primaryDiagnosis": "Fractured Tibia",
        "insuranceProvider": "UnitedHealthcare",
        "insuranceId": "UHC-556203",
        "emergencyContact": {
            "name": "Wei Chen",
            "relationship": "Father",
            "phone": "(555) 456-7890",
        },
        "medications": [
            {"name": "Ibuprofen", "dosage": "600mg", "frequency": "Every 6 hours"},
            {"name": "Acetaminophen", "dosage": "500mg", "frequency": "As needed"},
        ],
        "vitalSigns": {
            "heartRate": 68,
            "bloodPressure": "118/76",
            "temperature": 98.2,
            "oxygenSaturation": 99,
        },
        "medicalHistory": ["No significant medical history"],
        "notes": [
            "Post-surgery recovery on track.",
            "Physical therapy sessions to begin tomorrow.",
        ],
    },
    {
        "id": "PT-004",
        "firstName": "Robert",
        "lastName": "Williams",
        "dateOfBirth": "1960-01-28",
        "gender": "Male",
        "bloodType": "AB+",
        "nfcId": "MED-5681-NFC",
        "status": "active",
        "room": "4A-108",
        "admissionDate": "2026-02-12",
        "allergies": ["Codeine"],
        "primaryDiagnosis": "Atrial Fibrillation",
        "insuranceProvider": "Medicare",
        "insuranceId": "MCA-221847",
        "emergencyContact": {
            "name": "Sarah Williams",
            "relationship": "Daughter",
            "phone": "(555) 321-0987",
        },
        "medications": [
            {"name": "Warfarin", "dosage": "5mg", "frequency": "Daily"},
            {"name": "Digoxin", "dosage": "0.25mg", "frequency": "Daily"},
            {"name": "Lisinopril", "dosage": "10mg", "frequency": "Daily"},
            {"name": "Metformin", "dosage": "500mg", "frequency": "Twice daily"},
        ],
        "vitalSigns": {
            "heartRate": 88,
            "bloodPressure": "138/88",
            "temperature": 98.4,
            "oxygenSaturation": 96,
        },
        "medicalHistory": [
            "Coronary Artery Disease (diagnosed 2010)",
            "Type 2 Diabetes (diagnosed 2008)",
            "Knee replacement surgery (2017)",
        ],
        "notes": [
            "INR levels to be checked daily.",
            "Cardiology consult scheduled for tomorrow.",
        ],
    },
    {
        "id": "PT-005",
        "firstName": "Aisha",
        "lastName": "Patel",
        "dateOfBirth": "1991-05-09",
        "gender": "Female",
        "bloodType": "O-",
        "nfcId": "MED-7744-NFC",
        "status": "discharged",
        "room": "2C-315",
        "admissionDate": "2026-02-05",
        "allergies": ["Aspirin", "NSAIDs"],
        "primaryDiagnosis": "Post-Surgical Recovery (Cholecystectomy)",
        "insuranceProvider": "Cigna",
        "insuranceId": "CIG-339102",
        "emergencyContact": {
            "name": "Ravi Patel",
            "relationship": "Brother",
            "phone": "(555) 654-3210",
        },
        "medications": [
            {"name": "Acetaminophen", "dosage": "1000mg", "frequency": "Every 8 hours"},
            {"name": "Ondansetron", "dosage": "4mg", "frequency": "As needed"},
        ],
        "vitalSigns": {
            "heartRate": 72,
            "bloodPressure": "112/70",
            "temperature": 98.0,
            "oxygenSaturation": 99,
        },
        "medicalHistory": [
            "Gallstones (diagnosed 2025)",
            "Mild asthma (childhood)",
        ],
        "notes": [
            "Patient discharged in stable condition.",
            "Follow-up appointment in 2 weeks.",
        ],
    },
    {
        "id": "PT-006",
        "firstName": "Thomas",
        "lastName": "O'Brien",
        "dateOfBirth": "1955-12-17",
        "gender": "Male",
        "bloodType": "A+",
        "nfcId": "MED-9023-NFC",
        "status": "critical",
        "room": "ICU-301",
        "admissionDate": "2026-02-19",
        "allergies": ["Morphine", "Vancomycin"],
        "primaryDiagnosis": "Sepsis",
        "insuranceProvider": "Medicare",
        "insuranceId": "MCA-110392",
        "emergencyContact": {
            "name": "Patricia O'Brien",
            "relationship": "Wife",
            "phone": "(555) 789-0123",
        },
        "medications": [
            {"name": "Meropenem", "dosage": "1g", "frequency": "Every 8 hours IV"},
            {"name": "Norepinephrine", "dosage": "Titrated", "frequency": "Continuous drip"},
            {"name": "Hydrocortisone", "dosage": "100mg", "frequency": "Every 8 hours"},
        ],
        "vitalSigns": {
            "heartRate": 115,
            "bloodPressure": "90/58",
            "temperature": 102.8,
            "oxygenSaturation": 89,
        },
        "medicalHistory": [
            "Prostate cancer (remission since 2022)",
            "CABG surgery (2018)",
            "Chronic kidney disease stage 2",
        ],
        "notes": [
            "Hemodynamically unstable. Vasopressor support ongoing.",
            "Blood cultures pending. Infectious disease consult requested.",
        ],
    },
]
